#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.vag.privacyvis2018.entity
  mapperLocations: classpath:mapper/*.xml

server:
  port: 8888
  address: 10.76.0.159

#开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/privacy2018
    username: root
    password: 1864
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource